### PR TITLE
#147 Some contributor links are missing in Mockito release notes

### PR DESCRIPTION
**Pull request by mstachniuk**
ReleaseConfiguration().getTeam().getContributors() is used in different
places in code to define task's configuration. It needs to be always
the same reference during execution.

### CODE REVIEW

**Comment by szczepiq** [comment]
Thank you for looking into this issue and identifying the root cause!

Let me think about it a bit more before we merge it. I hope that there is a nicer approach than depending on reusing the same instance of a collection in different tasks. Although your idea does solve the problem :)

**Comment by mstachniuk** [comment]
The problem was that `ReleaseNotesPlugin` set always empty contributors list to `IncrementalReleaseNotes`:
https://github.com/mockito/mockito-release-tools/blob/2c567535a8a123cd9b2b86465e6b7bd47a9fe62c/src/main/groovy/org/mockito/release/internal/gradle/ReleaseNotesPlugin.java#L112

**Comment by szczepiq** [comment]
I needed to clear out my thinking about this configuration problem and wrote an essay on the topic here: https://github.com/mockito/mockito-release-tools/issues/147#issuecomment-301791747 Hopefully it is useful :)

I'd say we avoid sharing state between tasks as suggested in this PR. It may be surprising to the user, it makes it a bit harder to reconfigure tasks (you tweak one task but in fact, all other tasks that share the state are tweaked).

**Comment by mstachniuk** [comment]
Close and NOT merge this PR because of new solution in https://github.com/mockito/mockito-release-tools/pull/167 suggested by @szczepiq in https://github.com/mockito/mockito-release-tools/issues/147

**Pull request closed without merging**
